simulation_id = "Complete MultiprocessStandardSimulation"
algorithms_directory = "examples/algorithms/"
nodes = [ { node_id = "always_cooperate", algorithm = { file = "simple.py", object = "AlwaysCooperate" } },
          { node_id = "always_defect", algorithm = { file = "simple.py", object = "AlwaysDefect" } },
          { node_id = "grim_trigger", algorithm = { file = "grudge.py", object = "GrimTrigger" } },
          { node_id = "random_cooperation", algorithm = { file = "simple.py", object = "RandomCooperation" } },
          { node_id = "tit_for_tat", algorithm = { file = "tit_for_tat.py", object = "TitForTat" } },
          { node_id = "tit_for_two_tats", algorithm = { file = "tit_for_tat.py", object = "TitForTwoTats" } },
          { node_id = "two_tits_for_tat", algorithm = { file = "tit_for_tat.py", object = "TwoTitsForTat" } },
          { node_id = "firm_but_fair", algorithm = { file = "firm_but_fair.py", object = "FirmButFair" } } ]
simulation = { object = "MultiprocessStandardSimulation" }
simulation_arguments = { rounds = 200 }
simulation_data_output = "examples/rounds/complete_mss.json"
simulation_results_output = "examples/results/complete_mss.json"