simulation_id = "Noisy Complete StandardGenerationalSimulation for StandardSimulation"
algorithms_directory = "examples/algorithms/"
nodes = [ { node_id = "always_cooperate", algorithm = { file = "simple.py", object = "AlwaysCooperate" } },
          { node_id = "always_defect", algorithm = { file = "simple.py", object = "AlwaysDefect" } },
          { node_id = "grim_trigger", algorithm = { file = "grudge.py", object = "GrimTrigger" } },
          { node_id = "random_cooperation", algorithm = { file = "simple.py", object = "RandomCooperation" } },
          { node_id = "tit_for_tat", algorithm = { file = "tit_for_tat.py", object = "TitForTat" } },
          { node_id = "tit_for_two_tats", algorithm = { file = "tit_for_tat.py", object = "TitForTwoTats" } },
          { node_id = "two_tits_for_tat", algorithm = { file = "tit_for_tat.py", object = "TwoTitsForTat" } } ]
simulation = { object = "StandardGenerationalSimulation" }
generational_simulation = { object = 'StandardSimulation' }
simulation_arguments = { generations = 10, rounds = 200, noise = true, noise_per_mille = 250 }
simulation_data_output = "examples/rounds/noisy_complete_generational_ss.json"
simulation_results_output = "examples/results/noisy_complete_generational_ss.json"